### ISSUE TITLE
OpenSSL target not defined

### ISSUE THREAD

**Issue by memsharded** [conan-community/community#10]
Comes from: https://github.com/conan-io/conan/issues/2681

```
[settings]
os=Linux
os_build=Linux
arch=armv6
arch_build=armv6
compiler=gcc
compiler.version=4.8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

It's on a Raspberry Pi B1+. Conan version 1.1.1

Produces the error:
```
ERROR: OpenSSL/1.0.2l@conan/stable: Error in build() method, line 101
	self.unix_build(config_options_string)
while calling 'unix_build', line 169
	config_line = "./Configure %s -fPIC %s %s" % (config_options_string, target, extra_flags)
	UnboundLocalError: local variable 'target' referenced before assignment
```

Thanks @jasonwray for reporting

**Comment by jasonwray** [comment]
Yeah, same issue with 1.0.2n. I actually wasn't cross building, I was running it directly on the Raspberry Pi.

**Comment by lasote** [comment]
Hi, I just pushed openssl 1.0.2o improving the target management. Also I added some armv7hf builds to the travis CI. It will take some time to upload all the packages: https://travis-ci.org/conan-community/conan-openssl

**Comment by golyalpha** [comment]
I know this issue has been probably fixed for all arm architectures (armv6, armv7 and aarch64 are just a few of them), but I just wanted to note, that editing the conanfile.py script and adding 
`target = "%slinux-[arch here]" % target_prefix` works.

For those who for some reason need to use the version where the issue still exists.
