### ISSUE TITLE
[boost] Create a package for 1.64.0

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#89]
_From @liberforce on April 12, 2018 15:25_

Hi, would it be possible to have a branch for boost 1.64? There was a bunch of packages for that on conan-transit, but they're for conan < 1.0, and since the `Boost` -> `boost` renaming keeping old and new recipes doesn't work on Windows. This is because you can't have directories with the same name and different cases, so you can't parallel install a 1.64 recipe from conan-transit and `boost/1.66@conan/stable`.

I've successfully built a 1.64.0 based on your 1.66.0 recipe, by just [changing the version and checksums](https://github.com/liberforce/conan-boost/commit/1985ae5756f5929c0905427d22b4b1ab82f3cecb), but that's a bit stupid to have this kind of patching downstream. But I may have overlooked some problems with this approach and maybe just adapting your old 1.64 recipe would be better, I don't know.

So, could you please provide a 1.64 conan package that would be published on conan-center (maybe in `testing` channel, or `legacy` channel if you don't want to officially support that)? This will help people like me that can't depend on a too recent boost (we're still using 1.59 but I found that by using 1.64 our software would still build, but not with 1.66).

Thanks.

_Copied from original issue: conan-community/conan-boost#102_

**Comment by SSE4** [comment]
_From @helmesjo on June 28, 2018 22:10_

Any chance this could get some love @lasote ? 1.64.0 feels like a good, low-enough, version to support most of those older libs depending on "legacy boost".
Or is it a too big of a quest?

**Comment by SSE4** [comment]
_From @lasote on July 9, 2018 7:59_

You are right, the `1.64.0` recipe is very very outdated. I've not tried it but in addition to change the version and checksum we probably need to change the libraries list. Also, I needed to change some boost build related scripts in 1.66 (If I recall correctly) so it is possible that it fails too. 
The only way we can try it is opening a pull request and see how the CI goes. 
I would need some help here, this is not a quick request.

**Comment by SSE4** [comment]
_From @liberforce on July 9, 2018 10:1_

I was able to build boost 1.64 on Windows and Linux without problems, but didn't perform thourough testing on the generated binaries, so yeah, that might be more complicated.
I've created a PR against release/1.64, so there are lots of commits due to all the 1.64 → 1.66 activity, but mine is trivial. Let's see what the CI thinks about it.

**Comment by michaelmaguire** [comment]
I had issues with more recent versions of boost:

https://github.com/boostorg/build/issues/299#issuecomment-419433128

**Comment by liberforce** [comment]
@michaelmaguire : This bug is about 1.64, so I fail to see the relation with your comment...

**Comment by michaelmaguire** [comment]
@liberforce  The [highlighted issue](https://github.com/boostorg/build/issues/299#issuecomment-419433128) was introduced somewhere between 1.60 (which builds for me on Windows) and 1.67 where it appears to have been fixed.  Was only pointing it out in case your testing didn't cover that case.

**Comment by liberforce** [comment]
@michaelmaguire : 1.64.0 Build for me both on Windows 2016 Server and Ubuntu 16.04, but maybe the options are different.

**Comment by SSE4** [comment]
@liberforce do you still need branch for 1.64.0?

**Comment by liberforce** [comment]
That branch is old and existed prior to the package name change (Boost → boost). Existing packages never migrated from the deprecated `conan-transit` repository. Since then I tried to use boost 1.68. I'm almost there, but still have a small build issue.

**Comment by SSE4** [comment]
@liberforce okay, lemme know if you need any help
I've also found PR - is it still actual one?  https://github.com/conan-community/conan-boost/pull/126

**Comment by liberforce** [comment]
Yeah, the point was to just add [this commit](https://github.com/conan-community/conan-boost/pull/126/commits/918652334c8229e1eda3fc85aa50d64a0cd9aab9) on top of the 1.66.0 branch. Couldn't find a way to do that nicely at that time though. Merging the whole 1.66 branch into 1.64, and applying that commit on top should be enough.

**Comment by SSE4** [comment]
@liberforce I think now it's done, I've fixed build and merged changes to 1.64 branch, please give a try

**Comment by liberforce** [comment]
@SSE4 tested today, built both on Ubuntu 16.04 and Windows 2016 Server.
Thanks for pushing this !

**Comment by SSE4** [comment]
okay, I am closing the issue then
